-- 2026-09-17 — P&L: full expense breakdown + washing + marketplace-fee hybrid.
--
-- ⚠️ SUPERSEDED — DO NOT RUN THIS FILE. Run
--    db/2026-09-17-pl-cn-allocation-and-portal-real.sql instead (once).
--    It contains THIS file's full definitions as a prefix AND the later
--    2026-09-17 (late) changes on top.
--
-- WHY: this file's original body used `CREATE OR REPLACE VIEW` to change
-- the MIDDLE of pl_dashboard_by_month_view's column list (inserting
-- portal_expenses_25pct before net_earn). Postgres rejects that with
--
--   ERROR 42P16: cannot change name of view column "net_earn" to
--   "portal_expenses_25pct"
--
-- because CREATE OR REPLACE VIEW may only APPEND columns — it can never
-- rename, reorder, or insert between existing ones. The month view had
-- never been rebuilt with the 25% column, so "OR REPLACE" was actually a
-- column-list change → the error the user hit in Supabase. The company
-- view was also not re-runnable after the late changes (same 42P16, its
-- portal_expense_effective_inr was inserted mid-list relative to the
-- already-migrated DB state).
--
-- The single live migration is now the later file, which fixes both by
-- using `DROP VIEW ... CASCADE;` + full `CREATE VIEW` (column list may be
-- whatever we want) and re-creating everything that hangs off the views'
-- types afterwards. That file = THIS file's content + the real-portal +
-- CN-net changes. This stub stays so nobody re-runs a stale file from
-- git history.
--
-- Original intent (all preserved in the live file):
--   * 5 expense breakdown columns (courier / duty / purchase /
--     note-adjustments / washing / old CSV history)
--   * washing chalans auto-joi P&L (no manual Expenses entry)
--   * matched Etsy/eBay/Amazon fees + bank_inflow_inr columns
