"use client";

// 2026-08-12 (round 10): "JITNI FILE BAN RAHI HAI SABKI PDF FILE UNKE SAME
// DOWNLOAD KARNE KA OPTION HONA CHAHIYE JESE PO KA INVOICE BAN GAYA" —
// the existing PO Invoice "PDF download" is really just window.print() on
// a normal page with @media print CSS hiding everything outside one
// #id'd area (see src/app/dashboard/invoices/[id]/invoice-view.tsx). That
// pattern was copy-pasted into 4+ other pages already; this pulls it into
// one shared pair of components so every new printable view (Purchase
// Bill, Courier Bill, Duty & Tax Bill, the 2 new reports, Party Ledger)
// uses it the same way instead of re-copying the CSS block again.
//
// 2026-08-19 fix (part 1) — "ladger download karte hai to sirf single page
// hi download kyu hota hai": `position: fixed; inset: 0` pinned the
// printable area to the browser's on-screen viewport, which in print/PDF
// output clips it to a single page. Chrome's print engine only paginates
// content that flows in normal document position; `fixed`/`absolute`
// positioning both opt an element OUT of that flow and pin it to one page.
// Switched to plain `static` positioning.
//
// 2026-08-19 fix (part 2) — this alone turned out NOT to be enough: the
// user re-reported the exact same single-page symptom after this first
// fix was live. Root cause #2: `src/app/dashboard/layout.tsx`'s shell
// pins the WHOLE dashboard to the viewport height and clips overflow —
// `h-screen overflow-hidden` on the outer flex row, another
// `overflow-hidden` on the middle column, and `overflow-y-auto` on
// `<main>` (the "LEFT WINDOW AND TOP DESBORD LOCK KARO" fix from
// 2026-08-08, so the sidebar/header stay put while only `<main>`
// scrolls). Every printable page's content lives inside that `<main>`,
// so even with the printable area itself back in normal `static` flow,
// its scrollable/height-clamped ANCESTOR was still capping it to one
// viewport-height "page" — the print area's own CSS can't undo a
// constraint set by an element further up the tree. Confirmed with a
// Playwright print-to-PDF test reproducing the real shell structure:
// position:static alone still produced 1 page with content cut off;
// adding the rule below (neutralizing height/overflow on the shell's own
// utility classes, print-only) produced all 5 pages with every row
// present. Targets the exact Tailwind classes the shell uses
// (`h-screen`, `overflow-hidden`, `overflow-y-auto`) rather than walking
// the DOM, since this stylesheet has no way to reference the layout
// component directly — safe to do broadly here because everything except
// the printable area is already `visibility: hidden` above, so relaxing
// height/overflow on hidden ancestors has no visible effect except
// letting the real printable content's true height be measured and
// paginated correctly.
//
// 2026-09-17 — "har parkar ki report par niche right corner par likha hona
// chahiye ( jo bhi report invoice ya or kuch ) Genrated by nykoinfotech.com
// /OMS ... jis company ki report genrate ho rahi uska naam or logo bhi
// chahiye": every printable/downloadable document in the app goes through
// THIS one component (31 call sites — every report table, every bill/
// invoice/chalan report, Party Ledger, payslips, HR letters), so the
// branding footer is added here ONCE rather than copy-pasted 31 times.
// `companyName`/`companyLogoUrl` are optional — pages tied to one specific
// company's document (a bill report, an invoice, a party ledger) pass
// them; cross-company or company-agnostic pages (most /dashboard/reports/*
// tables, HR letters) just get the plain "Generated by" line, still
// satisfying "har parkar ki report par" without a misleading/wrong logo.
//
// `position: fixed` is used ONLY on this small footer, never on #${id}
// itself (see the 2026-08-19 fix above for exactly why that broke
// pagination) — a fixed-position DESCENDANT doesn't affect its own static
// ancestor's flow/pagination, and Chrome's print engine repeats a fixed
// element on every printed page, which is exactly what a footer needs.
//
// 2026-09-23 fixes — "HR letter print left menu bar ko cover karta hai" +
// "A4 ke page me header or footer ko sahi manage kar ke aaye":
//
// (a) STALE SELECTOR: the shell's root div (theme/themed-shell.tsx) was
// renamed `h-screen` → `h-dvh` on 2026-09-15 (a mobile-viewport fix), but
// this rule — last touched 2026-08-19, before that rename — still only
// neutralized `.h-screen`. So since 2026-09-15 the shell's fixed-height +
// overflow-hidden constraint was silently back in effect during print for
// EVERY one of the 31 PrintArea call sites (not just HR letters), which
// is exactly the single-page/clipped-content bug the 2026-08-19 fix was
// written to prevent. Added `.h-dvh` (and `.min-h-screen`/`.min-h-dvh` for
// the same reason) alongside `.h-screen` below.
//
// (b) SPACE-RESERVING SIDEBAR: `body * { visibility: hidden }` below makes
// the dashboard sidebar invisible but — unlike `display: none` —
// `visibility: hidden` does NOT remove an element from layout flow, so the
// sidebar's `w-72`/`w-60` column was still reserved during print, pushing/
// squeezing the actual printable content into the remaining width (read
// by the user as "print left menu bar ko cover karta hai"). Fixed at the
// source in dashboard-sidebar.tsx (`print:hidden` added directly to each
// of its 3 rendered states) rather than here, since this stylesheet has
// no selector for a component further up the tree it doesn't render.
//
// (c) A4 PAGE SIZE/MARGINS: no `@page` rule existed at all, so the actual
// paper size/margins were whatever the browser's print dialog defaulted
// to (often US Letter, and margins tight enough that the fixed-position
// footer above could sit right at the physical edge of the sheet). Added
// an explicit `@page { size: A4; margin: ... }` below so every printed/
// PDF'd document in the app — reports, bills, HR letters — consistently
// lays out on A4 with a real margin the header/footer content sits inside
// of, instead of relying on whatever the browser/OS happened to default
// to.
function ReportFooter({ companyName, companyLogoUrl }: { companyName?: string; companyLogoUrl?: string | null }) {
  return (
    <div className="print:fixed print:bottom-2 print:right-3 mt-6 flex items-center justify-end gap-2 border-t border-slate-200 pt-2 text-right print:mt-0 print:border-0 print:pt-0">
      {companyLogoUrl && (
        // eslint-disable-next-line @next/next/no-img-element -- print output; a plain <img> avoids next/image's runtime optimizer for a one-off small footer mark
        <img src={companyLogoUrl} alt="" className="h-4 w-4 rounded-sm object-contain" />
      )}
      <div className="leading-tight">
        {companyName && <div className="text-[9px] font-medium text-slate-500">{companyName}</div>}
        <div className="text-[8px] text-slate-400">Generated via NykoInfotech OMS · nykoinfotech.com</div>
      </div>
    </div>
  );
}

export function PrintArea({
  id,
  children,
  companyName,
  companyLogoUrl,
}: {
  id: string;
  children: React.ReactNode;
  /** Which company this specific document belongs to — omit for cross-company/company-agnostic pages. */
  companyName?: string;
  companyLogoUrl?: string | null;
}) {
  return (
    <>
      <style>{`
        @page {
          size: A4;
          margin: 14mm 12mm 16mm 12mm;
        }
        @media print {
          html, body { height: auto !important; overflow: visible !important; }
          .h-screen, .h-dvh, .min-h-screen, .min-h-dvh, .overflow-hidden, .overflow-y-auto {
            height: auto !important;
            max-height: none !important;
            overflow: visible !important;
          }
          body * { visibility: hidden; }
          #${id}, #${id} * { visibility: visible; }
          #${id} { position: static; width: 100%; }
        }
      `}</style>
      <div id={id}>
        {children}
        <ReportFooter companyName={companyName} companyLogoUrl={companyLogoUrl} />
      </div>
    </>
  );
}

export function PrintButton({ label = "🖨 Download PDF" }: { label?: string }) {
  return (
    <button
      type="button"
      onClick={() => window.print()}
      className="print:hidden rounded-lg bg-slate-800 px-3 py-1.5 text-xs font-semibold text-white transition hover:bg-slate-700"
    >
      {label}
    </button>
  );
}
